title: Emmanuel Cohen
logo: /assets/img/headshot_circle.png
description: Data Analyst Portfolio
#show_downloads: true
theme: jekyll-theme-minimal
# remote_theme: pages-themes/midnight@v0.2.0
# plugins:
# - jekyll-remote-theme
